FROM python:3.10-slim

WORKDIR /app

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG AWS_S3_IMAGE_BUCKET
ARG AWS_S3_METADATA_BUCKET
ARG BLACK_AND_WHITE_DIR
ARG CARTOONIZATION_DIR
ARG NUKKI_DIR

COPY requirements.txt .

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install opencv-python-headless

COPY . .

ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_KEY=$AWS_SECRET_KEY
ENV AWS_S3_IMAGE_BUCKET=$AWS_S3_IMAGE_BUCKET
ENV AWS_S3_METADATA_BUCKET=$AWS_S3_METADATA_BUCKET
ENV BLACK_AND_WHITE_DIR=$BLACK_AND_WHITE_DIR
ENV CARTOONIZATION_DIR=$CARTOONIZATION_DIR
ENV NUKKI_DIR=$NUKKI_DIR

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
